#!/bin/bash

# Setup script for local network testing
# This script helps you configure the app for testing on multiple devices

echo "🌐 Local Network Testing Setup"
echo "=============================="
echo ""

# Get local IP address
echo "🔍 Detecting your local IP address..."
if command -v hostname &> /dev/null; then
    LOCAL_IP=$(hostname -I | awk '{print $1}')
elif command -v ipconfig &> /dev/null; then
    # Windows WSL fallback
    LOCAL_IP=$(ip addr show eth0 | grep "inet\b" | awk '{print $2}' | cut -d/ -f1)
else
    LOCAL_IP="Unable to detect"
fi

if [ "$LOCAL_IP" == "Unable to detect" ] || [ -z "$LOCAL_IP" ]; then
    echo "❌ Could not automatically detect your IP address."
    echo ""
    echo "Please find your IP address manually:"
    echo "  - Windows: Run 'ipconfig' and look for IPv4 Address"
    echo "  - Mac/Linux: Run 'ifconfig' or 'ip addr show'"
    echo ""
    read -p "Enter your local IP address: " LOCAL_IP
fi

echo "✅ Your local IP address: $LOCAL_IP"
echo ""

# Create frontend .env.local
echo "📝 Creating frontend/.env.local..."
cat > frontend/.env.local << EOF
# Local Network Configuration
# Auto-generated by setup-local-network.sh

VITE_API_URL=http://${LOCAL_IP}:3001
VITE_WS_URL=ws://${LOCAL_IP}:3001
EOF

echo "✅ Created frontend/.env.local"
echo ""

# Display configuration
echo "📋 Configuration Summary"
echo "========================"
echo ""
echo "Frontend URL (for devices on your network):"
echo "  http://${LOCAL_IP}:3000"
echo ""
echo "Backend API URL:"
echo "  http://${LOCAL_IP}:3001"
echo ""
echo "WebSocket URL:"
echo "  ws://${LOCAL_IP}:3001"
echo ""

# Instructions
echo "🚀 Next Steps"
echo "============="
echo ""
echo "1. Start the app:"
echo "   npm start"
echo ""
echo "2. On your main device (laptop), open:"
echo "   http://${LOCAL_IP}:3000"
echo ""
echo "3. On other devices (phones, tablets), open:"
echo "   http://${LOCAL_IP}:3000"
echo ""
echo "4. Test the multi-user feature:"
echo "   - Device 1: Click 'Host Mode' and start broadcasting"
echo "   - Device 2: Click 'Join Session' and enter the code"
echo ""

# Firewall warning
echo "⚠️  Firewall Note"
echo "================"
echo "If other devices can't connect, you may need to allow these ports:"
echo "  - Port 3000 (Frontend)"
echo "  - Port 3001 (Backend)"
echo ""
echo "Windows: Run as Administrator:"
echo '  New-NetFirewallRule -DisplayName "Translation App" -Direction Inbound -Port 3000,3001 -Protocol TCP -Action Allow'
echo ""
echo "Linux:"
echo "  sudo ufw allow 3000/tcp"
echo "  sudo ufw allow 3001/tcp"
echo ""

echo "✨ Setup complete! Happy testing! ✨"
echo ""

