@echo off
REM Setup script for local network testing on Windows
REM This script helps you configure the app for testing on multiple devices

echo.
echo 🌐 Local Network Testing Setup
echo ==============================
echo.

echo 🔍 Detecting your local IP address...
echo.

REM Try to get IP address
for /f "tokens=2 delims=:" %%a in ('ipconfig ^| findstr /c:"IPv4 Address"') do (
    set LOCAL_IP=%%a
    goto :found_ip
)

:found_ip
REM Trim spaces
set LOCAL_IP=%LOCAL_IP: =%

if "%LOCAL_IP%"=="" (
    echo ❌ Could not automatically detect your IP address.
    echo.
    echo Please run 'ipconfig' and find your IPv4 Address
    echo Example: 192.168.1.100
    echo.
    set /p LOCAL_IP="Enter your local IP address: "
)

echo ✅ Your local IP address: %LOCAL_IP%
echo.

REM Create frontend .env.local
echo 📝 Creating frontend\.env.local...
(
echo # Local Network Configuration
echo # Auto-generated by setup-local-network.bat
echo.
echo VITE_API_URL=http://%LOCAL_IP%:3001
echo VITE_WS_URL=ws://%LOCAL_IP%:3001
) > frontend\.env.local

echo ✅ Created frontend\.env.local
echo.

REM Display configuration
echo 📋 Configuration Summary
echo ========================
echo.
echo Frontend URL (for devices on your network^):
echo   http://%LOCAL_IP%:3000
echo.
echo Backend API URL:
echo   http://%LOCAL_IP%:3001
echo.
echo WebSocket URL:
echo   ws://%LOCAL_IP%:3001
echo.

REM Instructions
echo 🚀 Next Steps
echo =============
echo.
echo 1. Start the app:
echo    npm start
echo.
echo 2. On your main device (laptop^), open:
echo    http://%LOCAL_IP%:3000
echo.
echo 3. On other devices (phones, tablets^), open:
echo    http://%LOCAL_IP%:3000
echo.
echo 4. Test the multi-user feature:
echo    - Device 1: Click 'Host Mode' and start broadcasting
echo    - Device 2: Click 'Join Session' and enter the code
echo.

REM Firewall warning
echo ⚠️  Firewall Note
echo ================
echo If other devices can't connect, you may need to allow these ports:
echo   - Port 3000 (Frontend^)
echo   - Port 3001 (Backend^)
echo.
echo Run as Administrator in PowerShell:
echo   New-NetFirewallRule -DisplayName "Translation Frontend" -Direction Inbound -Port 3000 -Protocol TCP -Action Allow
echo   New-NetFirewallRule -DisplayName "Translation Backend" -Direction Inbound -Port 3001 -Protocol TCP -Action Allow
echo.

echo ✨ Setup complete! Happy testing! ✨
echo.
pause

